# Generated by Django 5.1.2 on 2025-05-23 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Radio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_radio", models.CharField(max_length=100, unique=True)),
                ("siglas", models.CharField(max_length=20, unique=True)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("estado", models.CharField(max_length=100)),
                ("software", models.IntegerField(default=0)),
                (
                    "estado_suscripcion",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Inactivo", "Inactivo"),
                            ("Cancelado", "Cancelado"),
                        ],
                        default="Inactivo",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField(default=django.utils.timezone.now)),
                ("dias_restantes", models.IntegerField(default=0)),
                (
                    "paypal_subscription_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "paypal_custom_id",
                    models.CharField(blank=True, max_length=127, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
