# Generated by Django 5.1.2 on 2024-11-28 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_radio', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=100)),
                ('Software', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_suscripcion', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], max_length=50)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('dias_restantes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergoapp.radio')),
            ],
        ),
    ]
