# Generated by Django 5.1.2 on 2024-11-28 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadosuscripcion',
            name='user',
        ),
        migrations.AlterField(
            model_name='estadosuscripcion',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergoapp.radio', to_field='siglas'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='siglas',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
