# Generated by Django 5.1.2 on 2025-04-08 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergoapp', '0002_remove_estadosuscripcion_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='dias_restantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radio',
            name='estado_suscripcion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Suspendido', max_length=50),
        ),
        migrations.AddField(
            model_name='radio',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='EstadoSuscripcion',
        ),
    ]
