# Generated by Django 5.1.2 on 2025-04-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergoapp', '0003_radio_dias_restantes_radio_estado_suscripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='Software',
        ),
        migrations.AlterField(
            model_name='radio',
            name='estado_suscripcion',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Inactivo', max_length=50),
        ),
    ]
