# Generated by Django 5.1.2 on 2025-04-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergoapp', '0004_remove_radio_software_alter_radio_estado_suscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='software',
            field=models.CharField(default='-----', max_length=100),
        ),
        migrations.AlterField(
            model_name='radio',
            name='estado',
            field=models.CharField(default='-----', max_length=100),
        ),
    ]
