# Generated by Django 5.1.2 on 2025-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pergoapp", "0005_radio_software_alter_radio_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="radio",
            name="mercadopago_plan_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="mercadopago_preapproval_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="radio",
            name="estado",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="radio",
            name="software",
            field=models.CharField(max_length=100),
        ),
    ]
