# Generated by Django 5.1.2 on 2025-04-27 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pergoapp", "0007_alter_radio_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="radio",
            name="estado_suscripcion",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                default="Inactivo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="mercadopago_plan_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="radio",
            name="mercadopago_preapproval_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="radio",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="radio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
