# Generated by Django 5.1.2 on 2025-05-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pergoapp", "0008_alter_radio_estado_suscripcion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="radio",
            old_name="mercadopago_plan_id",
            new_name="paypal_subscription_id",
        ),
        migrations.RemoveField(
            model_name="radio",
            name="mercadopago_preapproval_id",
        ),
    ]
