# Generated by Django 5.1.2 on 2025-05-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pergoapp",
            "0009_rename_mercadopago_plan_id_radio_paypal_subscription_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="radio",
            name="paypal_custom_id",
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
