# Generated by Django 5.1.2 on 2025-05-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pergoapp", "0010_radio_paypal_custom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radio",
            name="estado_suscripcion",
            field=models.CharField(
                choices=[
                    ("Activo", "Activo"),
                    ("Inactivo", "Inactivo"),
                    ("Cancelado", "Cancelado"),
                ],
                default="Inactivo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="software",
            field=models.IntegerField(default=0),
        ),
    ]
